---
title: "Analytic Project Template"
author: "Anisha Nagpal"
date: "`r Sys.Date()`"
output: html_document
---

- date:"`r Sys.Date()`" sets the knitted file output date to the date you knit the file 

```{r}
#R automatically sets your working directory to the location of this .rmd file. However, this .rmd file path is your local cloned github folder. You should try to avoid saving knitted files here because they will not be accessible anywhere except locally on your computer. Additionally, Github can 'break' if it is trying to version control datasets. The code below sets your knitted output and any intermediary paths to Box
knitr::opts_knit$set(root.dir = "") #INSERT your box folder paths here 
setwd("~/Documents/my_project") #you can also use this code line to change your working directory in a code chunk, if you want to save an output somewhere else in your Box folder 
library(knitr)
knitr::opts_chunk$set(echo = TRUE) #makes sure when you knit, all of your code chunks are knitted too, and not just the code chunk output 
library(haven) #library to import .sav files 
library(dplyr) #many data managemnet functions, pipes, should also be included in tidyverse
library(ggplot2) #pretty plots 
library(kableExtra) #pretty tables 
library(lubridate) #managing dates in R
library(readr) #reading in .csv files
library(tidyverse) #many data management functions, pipes 
library(psych) #many data management and analysis functions 
library(lme4) #MLM models 
library(nlme) #MLM models + autoregression 
library(gridExtra)
library(lmerTest) #using lmerTest to get p-values
library(dfoptim) #optimizer to run MLM models with more iterations 
library(optimx) #optimizer to run MLM models with more iterations 
library(interactions) #functions to probe interactions 
library(emmeans) #functions for probing interactions
```

```{r}
setwd("plots") #In my box folder where I'm outputting everything, I made a subfolder called "plots." By putting this line of code, every file outputted by this code chunk will be saved in the plots subfolder 
```


