---
title: "prep_multilevel_spline_variables"
author: "Anisha Nagpal"
date: "`r Sys.Date()`"
output: html_document
---

```{r libraries and data import}
library(haven) #for reading files, especially useful for importing SPSS files 
library(tidyverse) #for data management and manipulation

#Import your dataset that you will be analyzing. If you are analyzing data across multiple studies, make sure you import the fully merged dataset (with level 1 data, example: each row is a day, clustered by participant ID) that you will be running your multilevel spline models on
#CLEAR3 daily surveys + cleartrialphase and meds

#This is clear3 daily for this example.
daily <- read_sav("C:/Users/anish/Box/00 - CLEAR Lab (Locked Folders)/02 - Data Management, Analysis, and Papers/Studies_Projects/CLEAR3/02_datasets/CLEAR3_DAILY/03_cleaned_data/2022-12-7_INTERIM ANALYSISforSTRAIN_clear3dailysurvey_phasemeds.sav")
```

Codebook for cycleday variables: https://docs.google.com/spreadsheets/d/13_wRtiV5pVnotzwDgJxqeDhXtSOQgLM5DurKQMp7krI/edit?usp=sharing

```{r creation of cycleday spline variables}
daily$cycleday13w0 <- as.numeric(daily$cycleday13w0) #go form -13 to +13, backward counting trumps forward counting, with 0 centered on menses 

daily$pretime <- daily$cycleday13w0
daily$posttime <- daily$cycleday13w0
#if pretime > -1, pretime = 0
daily$pretime <- ifelse(daily$pretime > -1, 0, daily$pretime)
daily$pretime_scale <- daily$pretime/13
#if postT < 0, postT = 0
daily$posttime <- ifelse(daily$posttime < 0, 0, daily$posttime)
daily$posttime_scale <- daily$posttime/13


#pretime_scale and posttime scale should range from -1 to 1, with menses centered on 0

#check how many participant ids
length(unique(daily$id))
#114 participants daily 
```


